package etf.iot.cloud.platform.services.dto;



import java.util.List;

/**
 * Class representing data generated by specific iot gateway app
 */
@lombok.Data
public class DeviceData {
    /**
     * Temperature data generated by the app.
     */
    private List<Data> temperatureData;
    /**
     * Fuel data generated by the app.
     */
    private List<Data> fuelData;
    /**
     * Load data generated by the app.
     */
    private List<Data> loadData;
    /**
     * Stats data regarding the app.
     */
    private List<Stats> deviceStats;
}
